name: SKD Media
favicon: null
layout_spectrum: 0.25053
typography_spectrum: 0.29557
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cbbc38'
    - '#313236'
    - '#808000'
    - '#ffff00'
    - '#ff0000'
  brandStrength: 0.6875
  lightness: 0.3125
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
