name: SKD Media
favicon: null
layout_spectrum: 0.25053
typography_spectrum: 0.29557
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a9b5b3'
    - '#0a0b10'
    - '#888983'
    - '#383546'
    - '#d6d7d2'
  brandStrength: 0.25
  lightness: 0.1875
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
