name: SKD Media
favicon: null
layout_spectrum: 0.25053
typography_spectrum: 0.29557
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f6f4f5'
    - '#7a7979'
    - '#c3c1c2'
    - '#6f1409'
  brandStrength: 0.25
  lightness: 0.3125
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
